spring.application.name=api-gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=read-only
management.endpoint.health.show-details=always

# Customer Service - DIRECT URL
spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/customers/**

# Product Service - Eureka + LoadBalancer
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**

# Order Service - Eureka + LoadBalancer
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=OrderLogging

spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET}